### ISSUE TITLE
Issues about implementing the model

### ISSUE THREAD

**Issue by JimLee1996** [swathikirans/violence-recognition-AVSS#1]
As is mentioned in the paper, 

> In the proposed model, we used the AlexNet model pre-trained on the ImageNet database as the CNN model for extracting frame level features.

where can we find the use of  pre-trained alexnet in the code?

Thank you.

**Comment by swathikirans** [comment]
The pre-trained models given in the links contain the final violence recognition model. The Alexnet model is present in it. You can load one of these models(provided in the download link) in torch to see how Alexnet is used.

**Comment by JimLee1996** [comment]
Thank you! I'll follow up and try to figure it out. ;-D
