### ISSUE TITLE
Would you mind publishing the training code of the paper? Thanks!

### ISSUE THREAD

**Issue by tigerlion2013** [swathikirans/violence-recognition-AVSS#2]

**Comment by swathikirans** [comment]
I have ported the code to pytorch. you can find the link

**Comment by tigerlion2013** [comment]
Thanks a lot. Actually, I have implemented the ConvLSTM by Pytorch. The results seem good.

Best,
Zhe
________________________________
发件人: Swathikiran Sudhakaran [notifications@github.com]
发送时间: 2018年6月8日 18:07
收件人: swathikirans/violence-recognition-AVSS
抄送: Liu, Zhe; Author
主题: Re: [swathikirans/violence-recognition-AVSS] Would you mind publishing the training code of the paper? Thanks! (#2)


I have ported the code to pytorch. you can find the link

―
