### ISSUE TITLE
links to the datasets

### ISSUE THREAD

**Issue by 1tron1** [swathikirans/violence-recognition-AVSS#5]
are there links to the datasets that could be placed either in PyTorch or lua repo?

**Comment by swathikirans** [comment]
You can get the datasets (videos) from the corresponding developers and extract the frames using any method of your own choice  (openCV or ffmpeg). Since I am not the owner of the datasets, I can't share them.

**Comment by ra1995** [comment]
Hi, I am trying to make the dataset the way you have specified.

I am saving the dataset as a tensor of dim(1x20x3x224x224) for one video of hockey dataset using torch.save method but it is giving me error on torch.load in your code. could you please share how you created the dataset file for the input. A code snippet will help me a lot.

Thank you.

**Comment by swathikirans** [comment]
Hi, could you tell what error you got? 
I used the following code to save the dataset which contains frames from all the videos in the dataset:

`dataset = torch.Tensor(50, 20, 3, 224, 224)
for i = 1, 50 do
    for k = 1, 20 do
      dataset[{{i}, {k}}] = image.scale(image.load(img_path_f .. vid_dir_f[i] .. '/img' .. k .. '.jpg'), 224, 224)
    end
end
torch.save('dataset', dataset)`

**Comment by ra1995** [comment]
This solved my problem, thanks a lot :)
